name: Metrics
on:
  schedule: [{cron: "0 9 * * *"}]  # daily 06:00 BRT
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: vgobbi8
          template: classic
          base: header, activity, repositories
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_topics: yes
          plugin_topics_limit: 12
          filename: metrics.svg
